### PR TITLE
Tc006 koray has been completed

### PR DESCRIPTION
**Pull request by basoglukoray1**
cool code here
cool code there

### CODE REVIEW

**Comment by basoglukoray1** [comment]
guys ?

**Comment by basoglukoray1** [comment]
can you see?

**Comment by basoglukoray1** [comment]
hello hello ?

**Comment by NattayaSdet** [comment]
Hello

**Comment by NattayaSdet** [comment]
Yes, I can see.

**Comment by erniedance** [comment]
i can see

**Comment by NazirMurtuzayev** [comment]
I can see too

**Comment by me1285** [comment]
yay we are all on the same page ....:)

**Comment by Kamala-GV** [comment]
Yes, now I see. Thanks

**Comment by me1285** [comment]
Guys let's follow each other here in GitHub

**Pull request merged**
